### ISSUE TITLE
Confusing instruction

### ISSUE THREAD

**Issue by pbywater** [foundersandcoders/postgres-workshop#8]
> Show a list of every book and their authors (one row per author)

I'm unsure what 'one row per author' is supposed to mean when the example answer's authors appear in multiple rows?

**Comment by jsms90** [comment]
It should read `one author per row` (as opposed to `multiple authors per row`)

I guess the idea is that, outside of a database tables, if you asked someone
> Show a list of every book and their authors

You would write a table like this:

| Name of book | Author(s) |
| --- | --- |
| My nice book title | John Smith & Jane Smith |
| Greatest book ever | Carly York |
| Yet another book title | Mr Bloggs & Mrs Bloggs |

that's why they've specified:
> (one row per author)

so students don't find it weird that the book name itself is repeated multiple times.

But in a database table, you need to list the book twice, like this:

| Name of book | Author |
| --- | --- |
| My nice book title | John Smith |
| My nice book title | Jane Smith |

That's something you would never normally write, because makes it look like there are two different books with the same title and each one is written by a different person.

Ironically, it was probably supposed to provide clarity :sweat_smile: 

The part that makes it extra confusing is that the same author just happens to have written multiple books, which is why you see authors appear in multiple rows.
